version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jkosi-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jkosi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jkosi-web-app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      # Link app directly to db service container
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: jkosi
      PAYLOAD_SECRET: ab6a1f695e4c043a3jkosiplatformsecretkey
      NEXT_PUBLIC_SERVER_URL: http://localhost:3000

volumes:
  pgdata:
